#! /usr/bin/bash

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
RAILS_ENV=production bundle exec rake db:migrate
STORED_ASSETS="${OPENSHIFT_DATA_DIR}/assets/gallery"
LIVE_ASSETS="${OPENSHIFT_REPO_DIR}/public/assets"

# Ensure our stored assets directory exists
if [ ! -d "${STORED_ASSETS}" ]; then
    echo " Creating permanent assets directory"
    mkdir -p "${STORED_ASSETS}"
fi

# Create symlink to stored assets unless we're uploading our own assets
if [ -d "${LIVE_ASSETS}" ]; then
    echo " WARNING: Assets included in git repository, not using stored assets"
else
    echo " Restoring stored assets"
    ln -sf "${STORED_ASSETS}" "${LIVE_ASSETS}/gallery"
fi
popd > /dev/nulle
